# 개발 환경
spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao