spring:
  config:
    activate:
      on-profile: prod

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://api.7-together.kro.kr/login/oauth2/code/kakao