name: together-server CI/CD

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 1. Git checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: ./gradlew clean build -x test

      - name: Create env files
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Upload Jar and .env to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: |
              build/libs/*.jar
              .env
            target: ~/deploy/

      - name: Run Spring Boot App on EC2
        uses: appleboy/ssh-action@0.1.7
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              sudo systemctl restart mysql
              sudo systemctl restart redis
              pkill -f 'java -jar' || true
              cd ~/deploy
              nohup env $(cat .env | xargs) java -jar *.jar > app.log 2>&1 &


