name: together-server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository Code Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. JDK install
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Spring Boot Project Build
      - name: Build Spring Boot project
        run: |
          cd backend
          ./gradlew clean build -x test

      # 4 EC2로 jar 업로드
      - name: Upload Jar to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            backend/build/libs/backend-0.0.1-SNAPSHOT.jar
          target: ~/deploy/
          strip_components: 3

      # 5. EC2로 run.sh 업로드
      - name: Upload run.sh to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: |
                backend/run.sh
            target: ~/deploy/
            strip_components: 0

      # 7. EC2에서 Spring Boot 실행
      - name: Run Spring Boot on Ec2
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              echo "[✅ 배포 스크립트 실행]"
              cd ~/deploy
              sudo systemctl restart mysql
              sudo systemctl restart redis
              pkill -f 'java -jar' || true
              nohup env $(cat .env | xargs) java -jar backend-0.0.1-SNAPSHOT.jar > app.log 2>&1 & disown
              echo "[✅ 실행 완료. 로그 보기: tail -f ~/deploy/app.log]"
                
                
              
          

